language: c

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

install:
  - sudo apt-get install luarocks
  - sudo luarocks install busted

script: busted
